const salgadoJson = [
    {id:1,
    name:'Coxinha',
    img:'images/coxinha.png',
    price:22.50,
    sizes:['50 unidades'],
    description:'Descrição da salgado em mais de uma linha muito legal bem interessante'},

    {id:2, 
    name:'Bolinha de queijo', 
    img:'images/queijo.png', 
    price:25.00, 
    sizes:['50 unidades'], 
    description:'Descrição da salgado em mais de uma linha muito legal bem interessante'},

    {id:3,
    name:'Camarão c/ Catupiry',
    img:'images/camarao.png',
    price:15.00,
    sizes:['10 unidades'],
    description:'Descrição da salgado em mais de uma linha muito legal bem interessante'},

    {id:4,
    name:'Salsicha',
    img:'images/salsicha.png',
    price:20.00,
    sizes:['50 unidades'],
    description:'Descrição da salgado em mais de uma linha muito legal bem interessante'},

    {id:5,
    name:'Kibe c/ catupiry',
    img:'images/kibeCatupiry.png',
    price:22.50,
    sizes:['50 unidades'],
    description:'Descrição da salgado em mais de uma linha muito legal bem interessante'},

    {id:6,
    name:'Carne moída',
    img:'images/carne.png',
    price:20.00,
    sizes:['50 unidades'],
    description:'Descrição da salgado em mais de uma linha muito legal bem interessante'},

    {id:7,
    name:'Variados',
    img:'images/todos.png',
    price:25.50,
    sizes:['50 unidades'],
    description:'Descrição da salgado em mais de uma linha muito legal bem interessante'},
]